name: Sync README

on:
  push:
    branches:
      - main  # Trigger when README.md is updated on the main branch

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Sync README.md across branches
      run: |
        git fetch origin
        git checkout $branch
        git merge main --no-edit
        git checkout main -- README.md
        if ! git diff --quiet; then
          git add README.md
          git commit -m "Sync README.md from main"
          git push origin $branch
        else
          echo "No changes needed for branch $branch"
        fi
