name: Sync README

on:
  push:
    branches:
      - main  # Trigger when README.md is updated on the main branch

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Sync README.md across branches
    run: |
    git fetch --all
    branches=$(git branch -r | grep -v "main" | grep -v "\->" | sed 's|origin/||')
    for branch in $branches; do
      git checkout $branch
      git checkout main -- README.md
      if ! git diff --ignore-cr-at-eol -- README.md; then
        echo "Updating README.md for branch $branch"
        git add README.md
        git commit -m "Sync README.md from main"
        git push origin $branch
      else
        echo "No changes to sync for branch $branch"
      fi
    done
